version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=credit_db
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=password123

  # Django Web Service
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: